### ISSUE TITLE
project status

### ISSUE THREAD

**Issue by matthieugayon** [mtthw-meyer/libdaisy-rust#7]
I just wanted to query the status of this project. I would really like to start experimenting with rust on the daisy hardware platform, but it looks like it still needs a bit of work to make it work flawlessly. And as a total noob in rust and embedded rust I am quite sure to be currently completely useless as a contributor :) 

How far do you think we are from that goal ? 
What do you see as the biggest chalenges ?

**Comment by mtthw-meyer** [comment]
Waiting for some upstream features in the stm32 crates to land before working on this more. Notably [I2S traits](https://github.com/rust-embedded/embedded-hal/pull/204) and similar maybe that are blocking [stm32h7xx I2S](https://github.com/stm32-rs/stm32h7xx-hal/pull/99). Once those land I'll look at where the DMA implementations are and try to fix any bandwidth issues with the raw I2S.
